### PR TITLE
[CHORE] Increase approve amount

### PR DESCRIPTION
**Pull request by spencerdezartsmith**

### CODE REVIEW

**Review by adamhannigan — APPROVED** [review]
LGTM.

We can also use the infinity amount - this is common practice and pops up in MetaMask approvals as "Infinity"

https://ethereum.stackexchange.com/questions/86928/does-the-approve-function-on-an-erc20-token-need-to-be-run-once-or-before-every

**Comment by c-py** [comment]
Also agree we should go for infinity amount

**Comment by spencerdezartsmith** [comment]
> Also agree we should go for infinity amount

Thanks guys. Will change.

**Review by c-py — APPROVED** [review]
LGTM!

**Pull request merged**
